tcms_tenants/urls.py
# Copyright (c) 2019-2021 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
# https://www.gnu.org/licenses/agpl-3.0.html

from django.urls import re_path
from tcms_tenants import views

app_name = "tcms_tenants"

urlpatterns = [
    re_path(r"^create/$", views.NewTenantView.as_view(), name="create-tenant"),
    re_path(r"^edit/$", views.UpdateTenantView.as_view(), name="edit-tenant"),
    re_path(r"^invite/$", views.InviteUsers.as_view(), name="invite-users"),
    re_path(
        r"^go/to/(?P<tenant>\w+)/(?P<path>.*)$",
        views.RedirectTo.as_view(),
        name="redirect-to",
    ),
]

tcms_tenants/models.py
# Copyright (c) 2019-2024 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
# https://www.gnu.org/licenses/agpl-3.0.html

import os

from django.db import models
from django.conf import settings

from django_tenants.models import TenantMixin, DomainMixin


class Tenant(TenantMixin):
    auto_create_schema = bool(os.environ.get("AUTO_CREATE_SCHEMA", True))
    auto_drop_schema = True

    name = models.CharField(max_length=100, db_index=True)
    created_on = models.DateTimeField(auto_now_add=True, db_index=True)
    paid_until = models.DateTimeField(null=True, blank=True, db_index=True)
    publicly_readable = models.BooleanField(default=False, db_index=True)
    authorized_users = models.ManyToManyField(to=settings.AUTH_USER_MODEL)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="tenant_owner"
    )
    organization = models.CharField(max_length=64, null=True, blank=True, db_index=True)
    extra_emails = models.CharField(
        null=True, blank=True, db_index=True, max_length=256
    )

    def __str__(self):
        return f"[{self.schema_name}] {self.name}"


def _authorized_user_str(self):
    return f"{self.user.username}@{self.tenant.name}"


Tenant.authorized_users.through.__str__ = _authorized_user_str


class Domain(DomainMixin):
    def __str__(self):
        return f"{self.domain} for {self.tenant}"

tcms_tenants/forms.py
# Copyright (c) 2019-2024 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
# https://www.gnu.org/licenses/agpl-3.0.html

import re

from django import forms
from django.forms.utils import ErrorList
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django_tenants.postgresql_backend import base as validators

from tcms.core.utils.mailto import custom_email_validators
from tcms_tenants import models
from tcms_tenants import utils

VALIDATION_RE = re.compile(r"^[a-z0-9]{1,63}$")


def _check_domain_name(name):
    """
    Because we use schema_name as sub-domains interchangeably
    we impose additional restriction on input values:
        alpha-numeric, 63 chars max
    """
    if not VALIDATION_RE.match(name):
        raise ValidationError(_("Invalid string"))


class NewTenantForm(forms.ModelForm):
    class Meta:
        model = models.Tenant
        exclude = ("authorized_users",)  # pylint: disable=modelform-uses-exclude

    schema_name = forms.CharField(
        max_length=63,
        # pylint: disable=protected-access
        validators=[
            validators._check_schema_name,
            _check_domain_name,
            utils.schema_name_not_used,
        ],
    )
    paid_until = forms.DateTimeField(required=False, widget=forms.HiddenInput)
    organization = forms.CharField(
        max_length=64, required=False, widget=forms.HiddenInput
    )
    extra_emails = forms.CharField(
        max_length=256, required=False, widget=forms.HiddenInput
    )


class InviteUsersForm(forms.Form):  # pylint: disable=must-inherit-from-model-form
    number_of_fields = 10

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for i in self.range:
            self.fields[f"email_{i}"] = forms.EmailField(
                required=False,
                validators=[custom_email_validators],
            )

    def clean(self):
        emails = set()

        for i in self.range:
            email = self.cleaned_data.get(f"email_{i}")
            if email:
                emails.add(email)

        self.cleaned_data["emails"] = emails

    @property
    def range(self):
        return range(self.number_of_fields)


class UpdateTenantForm(NewTenantForm):
    enabled_fields = (
        "name",
        "publicly_readable",
        "extra_emails",
    )

    def __init__(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        data=None,
        files=None,
        auto_id="id_%s",
        prefix=None,
        initial=None,
        error_class=ErrorList,
        label_suffix=None,
        empty_permitted=False,
        instance=None,
        use_required_attribute=None,
        renderer=None,
    ):
        super().__init__(
            data,
            files,
            auto_id,
            prefix,
            initial,
            error_class,
            label_suffix,
            empty_permitted,
            instance,
            use_required_attribute,
            renderer,
        )

        for field in self.fields:
            self.fields[field].disabled = field not in self.enabled_fields

        # remove validator which only makes sense when creating new tenants
        self.fields["schema_name"].validators.remove(utils.schema_name_not_used)

tcms_tenants/views.py
# Copyright (c) 2019-2024 Alexander Todorov <atodorov@otb.bg>
#
# Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
# https://www.gnu.org/licenses/agpl-3.0.html

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormView, UpdateView
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _

from tcms_tenants import utils
from tcms_tenants.forms import (
    InviteUsersForm,
    NewTenantForm,
    UpdateTenantForm,
    VALIDATION_RE,
)
from tcms_tenants.models import Tenant


@method_decorator(permission_required("tcms_tenants.add_tenant"), name="dispatch")
class NewTenantView(FormView):
    """
    Everybody is allowed to create new tenants.
    Depending on additional configuration they may have to pay
    for using them!
    """

    form_class = NewTenantForm

    def get_template_names(self):
        """
        Allow downstream installations to override the template. For example
        to provide a link to SLA or hosting policy! The overriden template
        can extend the base one if needed.
        """
        return ["tcms_tenants/override_new.html", "tcms_tenants/new.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tcms_tenants_domain"] = settings.KIWI_TENANTS_DOMAIN
        context["validation_pattern"] = VALIDATION_RE.pattern
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["initial"]["owner"] = self.request.user.pk
        return kwargs

    def form_valid(self, form):
        tenant = utils.create_tenant(form, self.request)
        # all is successfull so redirect to the new tenant
        return HttpResponseRedirect(utils.tenant_url(self.request, tenant.schema_name))


@method_decorator(permission_required("tcms_tenants.change_tenant"), name="dispatch")
class UpdateTenantView(UpdateView):
    model = Tenant
    form_class = UpdateTenantForm
    success_url = "/"

    def get_template_names(self):
        return ["tcms_tenants/override_edit.html", "tcms_tenants/new.html"]

    @staticmethod
    def check_owner(request):
        # super-user can edit all tenants
        if request.user.is_superuser:
            return None

        # tenant owner can edit their own tenant
        if request.user == request.tenant.owner:
            return None

        messages.add_message(
            request,
            messages.ERROR,
            _("Only super-user and tenant owner are allowed to edit tenant properties"),
        )
        return HttpResponseRedirect("/")

    def get(self, request, *args, **kwargs):
        return self.check_owner(request) or super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.check_owner(request) or super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.tenant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tcms_tenants_domain"] = settings.KIWI_TENANTS_DOMAIN
        context["validation_pattern"] = VALIDATION_RE.pattern
        context["form_action_url"] = reverse("tcms_tenants:edit-tenant")
        context["page_title"] = _("Edit tenant")
        return context


@method_decorator(login_required, name="dispatch")
class RedirectTo(RedirectView):  # pylint: disable=missing-permission-required
    """
    Will redirect to tenant.domain.domain/path!

    Used together with GitHub logins and the ``tenant_url``
    template tag!

    When trying to do GitHub login on a tenant sub-domain
    the HTML href will actually point to

    https://public.tenants.localdomain/login/github?next=/tenants/go/to/tenant/path

    instead of

    http://tenant.tenants.localdomain/login/github?next=path

    This is to prevent redirect_uri mismatch errors!
    """

    def get_redirect_url(self, *args, **kwargs):
        tenant = kwargs["tenant"]
        path = kwargs["path"]
        tenant_url = utils.tenant_url(self.request, tenant)
        return f"{tenant_url}/{path}"


@method_decorator(login_required, name="dispatch")
class InviteUsers(FormView):  # pylint: disable=missing-permission-required
    """
    Invite users to tenant via email.

    .. important::

        Anyone who is authorized for this tenant can invite others
        in the same way they can add them directly via the `Authorized users`
        menu!
    """

    form_class = InviteUsersForm
    template_name = "tcms_tenants/invite_users.html"

    def get(self, request, *args, **kwargs):
        if not utils.owns_tenant(request.user, request.tenant):
            messages.add_message(
                request,
                messages.ERROR,
                _("Only users who are authorized for this tenant can invite others"),
            )
            return HttpResponseRedirect("/")

        return super().get(self, request, *args, **kwargs)

    def form_valid(self, form):
        utils.invite_users(self.request, form.cleaned_data["emails"])

        return HttpResponseRedirect("/")

tcms_tenants/templates/tcms_tenants/invite_users.html
{% extends "base.html" %}

{% comment %}
Copyright (c) 2020-2024 Alexander Todorov <atodorov@otb.bg>

Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
https://www.gnu.org/licenses/agpl-3.0.html
{% endcomment %}

{% load i18n %}
{% load static %}

{% block head %}
    {{ form.media }}
{% endblock %}
{% block title %}
    {% trans "Invite users" %}
{% endblock %}


{% block contents %}
    <div class="container-fluid container-cards-pf">
        <form class="form-horizontal" action="{% url 'tcms_tenants:invite-users' %}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="{{ field.name }}">{% trans "Email" %}</label>
                <div class="col-sm-4 col-md-4 col-lg-4" {% if field.errors %}has-error{% endif %}">
                    <input type="text" id="{{ field.name }}" name="{{ field.name }}" value="{{ field.value|default:'' }}" class="form-control">

                    {{ field.errors }}
                </div>
            </div>
        {% endfor %}
            <button type="submit" class="btn btn-default btn-lg">{% trans "Save" %}</button>
        </form>
    </div>
{% endblock %}

tcms_tenants/templates/tcms_tenants/new.html
{% extends "base.html" %}

{% comment %}
Copyright (c) 2019-2023 Alexander Todorov <atodorov@otb.bg>
Copyright (c) 2022 Ivajlo Karabojkov <karabojkov@kitbg.com>

Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
https://www.gnu.org/licenses/agpl-3.0.html
{% endcomment %}

{% load i18n %}
{% load static %}

{% block head %}
    {{ form.media }}
{% endblock %}
{% block title %}
    {% trans "New tenant" as default_page_title %}
    {{ page_title|default:default_page_title }}
{% endblock %}


{% block contents %}
    {% url 'tcms_tenants:create-tenant' as form_url %}

    <div class="container-fluid container-cards-pf">
        <form class="form-horizontal" action="{{ form_action_url|default:form_url }}" method="post">
            {% csrf_token %}
            <input name="owner" type="hidden" value="{{ form.owner.value }}">

            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="id_name">{% trans "Name" %}</label>
                <div class="col-sm-11 col-md-8 col-lg-5 {% if form.name.errors %}has-error{% endif %}">
                    <input type="text" id="id_name" maxlength="{{ form.fields.name.max_length }}"
                           placeholder='{% trans "Company, team or project name" %}'
                           name="name" value="{{ form.name.value|default:'' }}"
                           class="form-control" required
                           {% if form.name.field.disabled %}disabled{% endif %}>
                    {{ form.name.errors }}
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="id_schema">{% trans "Schema" %}</label>
                <div class="col-sm-11 col-md-8 col-lg-5 {% if form.schema_name.errors %}has-error{% endif %}">
                    <div class="input-group">
                        <span class="input-group-addon">https://</span>
                        <input type="text" id="id_schema" maxlength="{{ form.fields.schema_name.max_length }}"
                               placeholder="commodore64"
                               name="schema_name" value="{{ form.schema_name.value|default:'' }}"
                               class="form-control" required
                               {% if form.schema_name.field.disabled %}disabled{% endif %}>
                        <span class="input-group-addon">.{{ tcms_tenants_domain }}</span>
                    </div>
                    {{ form.schema_name.errors }}
                    <p class="help-block">
                        {% trans "Validation pattern" %}: {{ validation_pattern }}
                    </p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-1 col-lg-1" for="id_publicly_readable">{% trans "Publicly readable" %}</label>
                <div class="col-md-3 col-lg-3 {% if form.publicly_readable.errors %}has-error{% endif %}">
                    <input class="bootstrap-switch" name="publicly_readable" type="checkbox"
                        {% if form.publicly_readable.value %}checked{% endif %}
                        {% if form.publicly_readable.field.disabled %}disabled{% endif %}
                        data-on-text="{% trans 'Yes' %}" data-off-text="{% trans 'No' %}">
                    {{ form.publicly_readable.errors }}
                </div>
            </div>

            {% block extra_contents %}
                {{ form.paid_until }}
            {% endblock %}
            <button type="submit" class="btn btn-default btn-lg">{% trans "Save" %}</button>
        </form>
    </div>

    {% if object %}
    <div class="col-sm-11 col-md-6 col-lg-6" style="padding-left: 10px;">
        {% trans "Tenant logo" as card_title %}
        {% include 'include/attachments.html' %}
    </div>
    {% endif %}
{% endblock %}

tcms_tenants/templates/tcms_tenants/tenant_name.html
{% comment %}
Copyright (c) 2022 Ivajlo Karabojkov <karabojkov@kitbg.com>
Copyright (c) 2022-2024 Alexander Todorov <atodorov@otb.bg>

Licensed under GNU Affero General Public License v3 or later (AGPLv3+)
https://www.gnu.org/licenses/agpl-3.0.html
{% endcomment %}

<a class="navbar-brand" href="/">
    {% if tenant_logo %}
    <img
        src="{{ tenant_logo.attachment_file.url }}"
        alt="{{ tenant_name }}"
        title="{{ tenant_name }}"
        style="max-height: 20px"
    />
    {% else %}
    <span>{{ tenant_name }}</span>
    {% endif %}
</a>